### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by jasonday** [goldfire/miniTip#14]
may be possible to use ajax without any code changes - I haven't tested this yet, but something like this might work:
(pseudocode)

show: function(content){
        if (content.html() == "") {
            $.get("/ajax.html", function(html){
                content.html(html);
            });
        }
    }

**Comment by goldfire** [comment]
You've got the basic idea there, though I'd start the AJAX call on render instead of show (will work either way). Try something like this:

``` javascript
render: function() {
    $.get('/ajax.html', function(html) {
        $('#miniTip_c').html(html);
    }
}
```

I usually set the content to be a loading icon that then gets replaced when the AJAX loads. You can see a working example of this at http://goldfire.me/James.
